version: "3"

services:
  hass:
    container_name: hass
    restart: always
    network_mode: host
    ports:
      - 8123:8123
    volumes:
      - "${HASS_CONFIG}:/config"
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Los_Angeles
    image: homeassistant/home-assistant:stable

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - DOCKER_IP=${DOCKER_IP}
    ports:
      - 3000:3000
    volumes:
      - ./configurations/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./configurations/grafana/dashboards:/etc/grafana/provisioning/dashboards

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    network_mode: host
    ports:
      - 9090:9090
    volumes:
      - ./configurations/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Los_Angeles'
      WEBPASSWORD: '${PIHOLE_PASSWORD}'
      DNS1: '1.1.1.1'
      DNS2: '8.8.8.8'
    volumes:
      - './data/etc-pihole/:/etc/pihole/'
      - './data/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
