version: "3"

services:
  hass:
    container_name: hass
    restart: unless-stopped
    privileged: true
    network_mode: host
    ports:
      - 8123:8123
    volumes:
      - "${HASS_CONFIG}:/config"
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=America/Los_Angeles
    image: "ghcr.io/home-assistant/home-assistant:stable"
    devices:
      - /dev/hci0:/dev/hci0

  #grafana:
  #  container_name: grafana
  #  image: grafana/grafana:7.3.4
  #  restart: always
  #  environment:
  #    - GF_SECURITY_ALLOW_EMBEDDING=true
  #    - DOCKER_IP=${DOCKER_IP}
  #    - GF_INSTALL_PLUGINS=grafana-piechart-panel,farski-blendstat-panel
  #      - GF_AUTH_ANONYMOUS_ENABLED=true
  #  ports:
  #    - 3000:3000
  #  volumes:
  #    - ./configurations/grafana/datasources:/etc/grafana/provisioning/datasources
  #    - ./configurations/grafana/dashboards:/etc/grafana/provisioning/dashboards
  #    - ./data/grafana:/var/lib/grafana

  #prometheus:
  #  container_name: prometheus
  #  image: prom/prometheus
  #  network_mode: host
  #  restart: always
  #  ports:
  #    - 9090:9090
  #  volumes:
  #    - ./configurations/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml

        #pihole:
        #container_name: pihole
        #image: pihole/pihole:latest
        #restart: unless-stopped
        #ports:
        #- "53:53/tcp"
        # - "53:53/udp"
        #- "67:67/udp"
        #- "80:80/tcp"
        #- "443:443/tcp"
        #environment:
        #TZ: 'America/Los_Angeles'
        #WEBPASSWORD: '${PIHOLE_PASSWORD}'
        #DNS1: '1.1.1.1'
        #DNS2: '8.8.8.8'
        #volumes:
        #- './data/etc-pihole/:/etc/pihole/'
        #- './data/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        #cap_add:
        #- NET_ADMIN

        #pihole_exporter:
        #container_name: pihole_exporter
        #image: ekofr/pihole-exporter:0.0.9
        #restart: unless-stopped
        #ports:
        #- 9617:9617
        #environment:
        # - PIHOLE_HOSTNAME=192.168.0.180
        #- "PIHOLE_PASSWORD=${PIHOLE_PASSWORD}"
        #- PORT=9617
        #- INTERVAL=30s
  
        # grafana_gateway:
        #container_name: grafana_gateway
        #build:
        # context: ./apps/docker/grafana_gateway/
        #ports:
        #- 4545:4545
        #volumes:
        #- ./apps/docker/grafana_gateway/config:/app/config:ro

  #gw1000_exporter:
  #  container_name: gw1000_exporter
  #  build:
  #    context: ./apps/docker/gw1000_exporter/
  #  ports:
  #   - 7689:7689
  #  restart: unless-stopped

 #influxdb:
 #container_name: influxdb
 #  image: arm32v7/influxdb
 #  ports:
 #    - 8006:8006
 #  volumes:
 #    - ./data/influxdb:/var/lib/influxdb
