version: "3"

services:
  hass:
    container_name: hass
    restart: always
    network_mode: host
    ports:
      - 8123:8123
    volumes:
      - "${HASS_CONFIG}:/config"
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Los_Angeles
    image: homeassistant/home-assistant:stable

  grafana:
    container_name: grafana
    ports:
      - 3000:3000
    image: grafana/grafana

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    network_mode: host
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
