# From: https://prometheus.io/docs/guides/node-exporter/

global:
  scrape_interval: 15s

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['localhost:9100']
- job_name: fastdotcom
  static_configs:
  - targets: ['localhost:3456']