# From: https://prometheus.io/docs/guides/node-exporter/

global:
  scrape_interval: 15s

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['localhost:9100']
- job_name: fastdotcom
  static_configs:
  - targets: ['localhost:3456']
- job_name: pihole
  static_configs:
  - targets: ['localhost:9617']
- job_name: gw1000
  static_configs:
  - targets: ['localhost:7689']