{
 "title": "Hardware Monitor",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m])",
     "legendFormat": "Receive: {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[1m])",
     "legendFormat": "Transmit: {{device}}"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"system\"}[1m])",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Fast.com download speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "expr": "download_speed_in_bytes" }
   ]
  }
 ]
}